[package]
name = "beaches_front"
version = "0.1.0"
edition = "2021" 

[dependencies]
actix-web = "4" 
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
diesel = { version = "1.4.4", features = ["chrono", "postgres", "r2d2", "uuidv07", "serde_json"] }
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
derive_more = "0.99.5"
actix-session = { version = "0.7.1", features = ["cookie-session"] }
actix-rt = "^1.1.1"
awc = { version = "3", features = ["rustls"] }
clap = { version = "3", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["json"] }
sailfish = "0.4.0"
sailfish-macros = "0.4.0"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

